ToDoApp/Models/ErrorViewModel.cs
using System;

namespace ToDoApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoApp/Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApp.Models
{
    public class Task
    {
        [Key]
        public int TaskId { get; set; }

        [Column(TypeName = "text")]
        [Required]
        public string Text { get; set; }

        [Column(TypeName = "varchar(20)")]
        public string Color { get; set; }
    }
}

ToDoApp/Models/TaskContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToDoApp.Models
{
    public class TaskContext:DbContext
    {
        public TaskContext(DbContextOptions<TaskContext> options):base(options)
        {
             
        }

        public DbSet<Task> Tasks { get; set; }
    }
}

ToDoApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoApp/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class TasksController : Controller
    {
        private readonly TaskContext _context;

        public TasksController(TaskContext context)
        {
            _context = context;
        }

        // GET: Tasks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tasks.ToListAsync());
        }

        // GET: Tasks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TaskId,Text,Color")] Models.Task task)
        {
            if (ModelState.IsValid)
            {
                _context.Add(task);
                task.Color = "lightblue";
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(task);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            return View(task);
        }

        public async Task<IActionResult> EditColorBlue(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            task.Color = "lightblue";
            _context.Update(task);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> EditColorPink(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            task.Color = "pink";
            _context.Update(task);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> EditColorYellow(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            task.Color = "lightgoldenrodyellow";
            _context.Update(task);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TaskId,Text,Color")] Models.Task task)
        {
            if (id != task.TaskId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(task);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskExists(task.TaskId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(task);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var task = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(task);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool TaskExists(int id)
        {
            return _context.Tasks.Any(e => e.TaskId == id);
        }
    }
}

ToDoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="//cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Tasks" asp-action="">ToDoApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ToDoApp 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoApp/Views/Tasks/Create.cshtml
@model ToDoApp.Models.Task

@{
    ViewData["Title"] = "Create";
}

<h3>Create new task:</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="width: 40em;">
                <label asp-for="Text" class="control-label"></label>
                <textarea asp-for="Text" class="form-control" id="content1"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            
@*            <script>
                        CKEDITOR.replace( 'editor1' );
            </script>*@
            <div class="form-group">
                <input type="submit" value="Create Task" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i class="fas fa-arrow-left"></i> Back to Tasks</a>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        var editor = CKEDITOR.replace("content1");
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoApp/Views/Tasks/Delete.cshtml
@model ToDoApp.Models.Task

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Task</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TaskId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ToDoApp/Views/Tasks/Details.cshtml
@model ToDoApp.Models.Task

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Task</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TaskId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ToDoApp/Views/Tasks/Edit.cshtml
@model ToDoApp.Models.Task

@{
    ViewData["Title"] = "Edit";
}

<h3>Edit task</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TaskId" />
            <div class="form-group" style="width: 40em;">
                <label asp-for="Text" class="control-label"></label>
                <textarea asp-for="Text" class="form-control" id="content1"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
                <input type="hidden" asp-for="Color" class="form-control" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i class="fas fa-arrow-left"></i> Back to Tasks</a>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        var editor = CKEDITOR.replace("content1");
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoApp/Views/Tasks/Index.cshtml
@model IEnumerable<ToDoApp.Models.Task>

@{
    ViewData["Title"] = "Index";
}

<h3 class="text-center">Tasks to do:</h3>

<div class="border box-shadow mb-3 text-center rounded tasks__container link" style="min-height: 75vh;">
    @foreach (var item in Model)
    {
        <div style="background-color: @item.Color" class="rounded border box-shadow mb-3 task__container attachment">
            <div disabled class="text__container">
                @Html.Raw(item.Text)
            </div>
            <div class="right-icons">
                <a asp-action="Edit" asp-route-id="@item.TaskId" class="icon-edit" title="Edit task"><i class="fas fa-edit"></i></a>
                <a asp-action="Delete" asp-route-id="@item.TaskId" class="icon-delete" title="Delete task"><i class="fas fa-times"></i></a>
            </div>
            <div class="left-icons">
                <a asp-action="EditColorBlue" asp-route-id="@item.TaskId" class="icon-color" title="Lightblue" style="color: blue"><i class="fas fa-square"></i></a>
                <a asp-action="EditColorPink" asp-route-id="@item.TaskId" class="icon-color" title="Pink" style="color: #E75480"><i class="fas fa-square"></i></a>
                <a asp-action="EditColorYellow" asp-route-id="@item.TaskId" class="icon-color" title="Yellow" style="color: yellow"><i class="fas fa-square"></i></a>
            </div>
            <div class="click-to-lift">
                Click on task to lift up
            </div>
        </div>


    }
    <div class="add-task">
        <div class="add-task__icon"><i class="fas fa-plus"></i></div>
        <div class="add-task__text">Click anywhere on the workspace to add new task</div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('.link').click(function () {
            window.location = "/Tasks/Create";
        });
        $(".attachment").on("click", function (event) {
            event.stopPropagation();
        });
    });
</script>